### ISSUE TITLE
Missing package.json in L731

### ISSUE THREAD

**Issue by ammbra** [Adobe-Marketing-Cloud/Summit2018#12]
Hello,

In L731 the ionic app seems to be missing package.json.

**Comment by davidjgonzalez** [comment]
@amol-anand - any idea on this?

**Comment by amol-anand** [comment]
@ammbra code updated with the package.json.

See 
* https://github.com/Adobe-Marketing-Cloud/Summit2018/tree/L731
* (Commit w change) https://github.com/Adobe-Marketing-Cloud/Summit2018/commit/d285ba6534dfdad8d457f96d8cbb807c0f627701

**Comment by davidjgonzalez** [comment]
Thanks @amol-anand!
