### ISSUE TITLE
we-retail-journel reference package

### ISSUE THREAD

**Issue by sandeepkumar03** [Adobe-Marketing-Cloud/Summit2018#9]
Lab guide for [Single Page Applications AEM](https://github.com/Adobe-Marketing-Cloud/Summit2018/blob/L737/L737_Robert.docx) integration mentions about in-context app editing (Exercise 11), but we-retail-journel is not part of git repository.

Is there a separate package required for this?

**Comment by davidjgonzalez** [comment]
Hi @sandeepkumar03  - unfortunately that package (and mostly because the supporting code) cannot be shared publically just yet. The team is working on the AEM Single Page App editor functionality - hopefully, these artifacts will be sharable around the June time-frame.

Sorry about that!

**Comment by sandeepkumar03** [comment]
Thanks @davidjgonzalez. It was listed in [AEM Features List](https://www.adobe.com/marketing-cloud/experience-manager/new-capabilities.html) list, so we thought it would be available.
